services:
  - type: web
    name: wummi-hang
    runtime: python
    plan: free
    autoDeploy: true
    healthCheckPath: /ping
    buildCommand: apt-get update && apt-get install -y libopus0 libopusfile0 libogg0 && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
